name: Build and deploy Angular app to Azure Web App - tariff-calculation-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app (production)
        run: npm run build --if-present -- --configuration production

      - name: Zip Angular dist folder
        run: |
          cd dist
          # replace 'tariff-calculation-ui' with your Angular project folder name from angular.json
          cd tariff-calculation-ui
          zip -r ../../app.zip .
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: app.zip

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tariff-calculation-ui'
          slot-name: 'Production'
          package: app.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DF2576EEA46947FCA432260539829A40 }}
