name: Build and deploy Angular app to Azure Web App - Tariff-Calculation-UI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: ${{secrets.AZURE_WEBAPP_NAME}} # Replace with your Azure Web App name
  BUILD_DIRECTORY: 'dist/testapprun/browser' # The output folder after 'ng build'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: Zip Angular dist folder
        run: zip -r release.zip ${{ env.BUILD_DIRECTORY }}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: dist/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-app
      - name: Unzip artifact
        run: unzip release.zip
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: './release.zip' # Deploy the created zip file
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1477BFBD1301490DBB7DA960E949B39A }}