name: Build and Deploy Angular to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Tariff-Calculation-UI
      - name: Build Tariff-Calculation-UI
        run: npm run build --prod

      # Zip the build output
      - name: Zip artifact for deployment
        run: |
          cd dist
          zip -r ../Tariff-Calculation-UI.zip Tariff-Calculation-UI
          cd ..

      # Upload build artifact (optional, for debugging/download)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tariff-Calculation-UI
          path: Tariff-Calculation-UI.zip

      # Deploy to Azure WebApp
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Tariff-Calculation-UI"   # Replace with your Azure WebApp name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: Tariff-Calculation-UI.zip
