name: Build and Deploy Angular SSR app to Azure Web App - tariff-calculation-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  APP_NAME: 'tariffcalculation' # <-- Replace with your Azure Web App name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies & build SSR
        run: |
          npm ci
          npm run build:ssr

      - name: Prepare artifact
        run: |
          mkdir deploy
          cp -r dist deploy/dist
          cp package.json deploy/
          cp package-lock.json deploy/

      - name: Zip artifact
        run: |
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: tariff-calculation-ui
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tariff-calculation-ui

      - name: Unzip artifact
        run: unzip release.zip -d .

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
